//
//  HXBLEDevice.h
//  HXJBLESDK
//
//  Created by JQ on 2019/4/17.
//  Copyright © 2019年 JQ. All rights reserved.
//

#import "HXBLEDeviceBase.h"

/** Bluetooth lock information, please enter HXBLEDeviceBase to view other attributes */
/** 蓝牙锁信息，其它属性请进入HXBLEDeviceBase查看 */
@interface HXBLEDevice : HXBLEDeviceBase


/**
en:
 Note:
1. [Administrator Authorization Code]:
  All Bluetooth interfaces are allowed to be called.
2. [Temporary user authorization code and normal user authorization code]:
  There are no OTA upgrade and delete Bluetooth lock permissions. Other Bluetooth interfaces have permissions. At present, these two authorization codes have the same permissions.
 */
/**
cn:
 注：
1. [管理员授权码] ：
  允许调用所有蓝牙接口。
2. [临时用户授权码和普通用户授权码] ：
  没有OTA升级和删除蓝牙锁这2个权限，其它蓝牙接口都有权限，目前这2个授权码权限一样。
 */




/**
en:
 Administrator authorization code
 */
/**
cn:
 管理员授权码
 */
@property (nonatomic, copy) NSString *adminAuthCode;

/**
en:
 General user authorization code
 */
/**
cn:
 普通用户授权码
 */
@property (nonatomic, copy) NSString *generalAuthCode;

/**
en:
 Temporary user authorization code
 */
/**
cn:
 临时用户授权码
 */
@property (nonatomic, copy) NSString *tempAuthCode;

/**
en:
 AES128 secret key generated by Bluetooth for subsequent business communication
 */
/**
cn:
 由蓝牙生成的AES128秘钥，供后续业务通信使用
 */
@property (nonatomic, copy) NSString *aesKey;

/**
en:
 Bluetooth lock MAC
 */
/**
cn:
 蓝牙锁MAC
 */
@property (nonatomic, copy) NSString *lockMac;

/**
en:
 Bluetooth lock type, generally the default value 5
 */
/**
cn:
 蓝牙锁类型，一般为默认值5
 */
@property (nonatomic, assign) int lockType;

/**
en:
 Initialization flag, the initFlag is automatically incremented every time the Bluetooth lock is successfully initialized
 */
/**
cn:
 初始化标志位，蓝牙锁每次初始化成功后initFlag自动递增
 */
@property (nonatomic, assign) long initFlag;

/**
en:
  Door lock create time
*/
/**
cn:
  门锁创建时间
*/
@property (nonatomic, assign) long lockCreateTime;

- (NSDictionary *)dicFromObject;

@end
