//
//  HXBluetoothLockHelper.h
//  JQBluetooth
//
//  Created by JQ on 2017/11/24.
//  Copyright © 2017年 JQ. All rights reserved.
//
#import <Foundation/Foundation.h>
#import "JQBLEDefines.h"

//数据模型 Data model
#import "HXOperationRecordHeader.h"//第一代蓝牙锁操作记录 Bluetooth lock operation record
#import "HXOperationRecord2Header.h"//第二代蓝牙锁操作记录 Bluetooth lock operation record
#import "HXKeyModel.h"//钥匙信息 Key information
#import "HXBLEDevice.h"
#import "HXBLEDeviceStatus.h"

//请求参数 Request parameter
#import "HXBLEAddPasswordKeyParams.h"//添加密码请求参数 Add password request parameter
#import "HXBLEAddOtherKeyParams.h"//添加卡片/遥控/指纹请求参数 Add card/remote control/fingerprint request parameters
#import "HXSetKeyEnableParams.h"//禁用或激活钥匙请求参数 Disable or enable key request parameters
#import "HXModifyKeyTimeParams.h"//修改钥匙有效期请求参数 Modify the key validity period request parameter
#import "HXDeleteKeyParams.h"//删除钥匙请求参数 Delete key request parameter
#import "HXSetSystemParameters.h"//设置系统参数请求参数 Set system parameter request parameters
#import "HXUnlockParams.h"//蓝牙开锁请求参数 Bluetooth unlock request parameters
#import "SHBLENetworkConfigParam.h"
#import "SHBLEAddBigDataKeyParam.h"
#import "SHBLEKeyValidTimeParam.h"
#import "SHBLEHotelLockSystemParam.h"

#import "HXBLESecureAuthProtocol.h"



@interface HXBluetoothLockHelper : NSObject

#pragma mark -设置一个蓝牙设备的基础配置信息 Set the basic configuration information of a Bluetooth device
///en:
/// Set the basic configuration information of a Bluetooth device,
/// Before calling the methods in HXBluetoothLockHelper, HXBluetoothNBHelper, HXBluetoothNBInfoHelper, startUpgradeWithMac,
/// you must call this method once.
/// If the subsequent interface parameters are updated,
/// you need to call this interface.
/// 1. [Administrator Authorization Code]:
/// All Bluetooth interfaces are allowed to be called.
/// 2. [Temporary user authorization code and normal user authorization code]:
/// There are no OTA upgrade and delete Bluetooth lock permissions.
/// Other Bluetooth interfaces have permissions. At present, these two authorization codes have the same permissions.
/// @param aesKey The communication key between the application and the Bluetooth lock (aesKey is generated by the Bluetooth lock, and the aesKey can be obtained in the HXBLEDevice that adds the Bluetooth lock callback)
/// @param authCode Authorization code (Bluetooth lock will generate 3 types of authorization codes, which will be obtained from the returned HXBLEDevice after the device is successfully added)
/// @param keyGroupId Represents the App user Id, which is used to distinguish different operating users in event reporting. Generally assigned by the server to ensure that there will not be multiple identical keyGroupIds in the same Bluetooth lock, value range: 900-4095
/// @param bleProtocolVersion Protocol version of Bluetooth lock
/// @param lockMac Bluetooth lock Mac address (use lowercase letters in lockMac)

///cn:
/// 设置一个蓝牙设备的基础配置信息，
/// 调用HXBluetoothLockHelper、HXBluetoothNBHelper、HXBluetoothNBInfoHelper、startUpgradeWithMac中的方法前，要先调用该方法一次，如果后续该接口参数有更新需要再调用该接口。
/// 1. [管理员授权码] ：
/// 允许调用所有蓝牙接口。
/// 2. [临时用户授权码和普通用户授权码] ：
/// 没有OTA升级和删除蓝牙锁这2个权限，其它蓝牙接口都有权限，目前这2个授权码权限一样。
/// @param aesKey 应用程序与蓝牙锁的通信密钥（aesKey由蓝牙锁生成，aesKey可在添加蓝牙锁接回调的HXBLEDevice中获取）
/// @param authCode 授权码（蓝牙锁会生成3种类型的授权码，添加设备成功后从返回的HXBLEDevice中获取）
/// @param keyGroupId 表示App用户Id，用于事件上报中区分不同的操作用户。一般由服务器分配保证在同一个蓝牙锁中不会出现多个相同的keyGroupId，取值范围：900-4095
/// @param bleProtocolVersion 蓝牙锁的协议版本
/// @param lockMac 蓝牙锁Mac地址（特别注意：lockMac中的字母要使用小写）
+ (void)setDeviceAESKey:(NSString *)aesKey
               authCode:(NSString *)authCode
             keyGroupId:(int)keyGroupId
     bleProtocolVersion:(int)bleProtocolVersion
                lockMac:(NSString *)lockMac;

///en:
/// Set the basic configuration information of a Bluetooth device, Pro version (Note: If the App cannot obtain the aesKey and authCode of the door lock, use this method)
/// For a Bluetooth lock, this method is mutually exclusive with'setDeviceAESKey:authCode:keyGroupId:bleProtocolVersion:lockMac'
/// Need to implement the protocol HXBLESecureAuthProtocol
/// Before calling the methods in HXBluetoothLockHelper, HXBluetoothNBHelper, HXBluetoothNBInfoHelper, HXBLEUpgradeHelper, you must call this method once. If the subsequent keyGroupId or bleProtocolVersion is updated, you need to call this method again
/// @param keyGroupId Represents the App user Id, which is used to distinguish different operating users in event reporting. Generally assigned by the server to ensure that there will not be multiple identical keyGroupIds in the same Bluetooth lock, value range: 900-4095
/// @param bleProtocolVersion Protocol version of Bluetooth lock
/// @param lockMac Bluetooth lock Mac address (use lowercase letters in Mac)
/// @param secureAuthObj For custom objects, a security authentication protocol needs to be implemented to achieve secure communication between the App and the Bluetooth lock (note: in the process of using the Bluetooth lock, please ensure that the object will not be released)

///cn:
/// 设置一个蓝牙设备的基础配置信息，Pro版本(注意：如果App无法获取到门锁的aesKey、authCode，则使用该方法)
/// 对一个蓝牙锁，该方法与'setDeviceAESKey:authCode:keyGroupId:bleProtocolVersion:lockMac'互斥
/// 需要实现协议HXBLESecureAuthProtocol
/// 调用HXBluetoothLockHelper、HXBluetoothNBHelper、HXBluetoothNBInfoHelper、HXBLEUpgradeHelper中的方法前，要先调用该方法一次，如果后续keyGroupId或bleProtocolVersion有更新，需要再次调用该方法
/// @param keyGroupId 表示App用户Id，用于事件上报中区分不同的操作用户。一般由服务器分配保证在同一个蓝牙锁中不会出现多个相同的keyGroupId，取值范围：900-4095
/// @param bleProtocolVersion 蓝牙锁的协议版本
/// @param lockMac 蓝牙锁Mac地址（Mac中的字母要使用小写）
/// @param secureAuthObj 自定义对象，需实现安全认证协议，以实现App与蓝牙锁的安全通信（注意：在使用蓝牙锁过程中，请确保该对象不会被释放）
+ (void)setKeyGroupId:(int)keyGroupId
   bleProtocolVersion:(int)bleProtocolVersion
              lockMac:(NSString *)lockMac
        secureAuthObj:(id<HXBLESecureAuthProtocol>)secureAuthObj;

#pragma mark -蓝牙开锁 Bluetooth unlock
///en:
/// Bluetooth unlock
/// @param mac Bluetooth lock mac address (use lowercase letters in Mac)
/// @param synchronizeTime Whether to calibrate the Bluetooth lock time; YES: unlock and calibrate the Bluetooth lock to the phone time; NO: unlock without calibrating the time;
/// @param block Result callback, power: door lock power (0~100), unlockingDuration: unlocking duration (for example, the unlocking duration is 6 seconds, then unlocking is not allowed within 6 seconds)

///cn:
/// 蓝牙开锁
/// @param mac 蓝牙锁mac地址（Mac中的字母要使用小写）
/// @param synchronizeTime 是否校准蓝牙锁时间；YES：开锁并给蓝牙锁校准为手机时间；NO：开锁不校准时间；
/// @param block 结果回调，power：门锁电量（0~100），unlockingDuration：开锁持续时间(例如开锁持续时间为6秒，则6秒内不允许开锁)
+ (void)unlockWithMac:(NSString *)mac
      synchronizeTime:(BOOL)synchronizeTime
      completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, NSString *mac, int power, int unlockingDuration))block;

///en:
/// Bluetooth unlock (multiple request parameters can be customized)
/// @param params Customize Bluetooth unlock request parameters
/// @param block Result callback, power: door lock power (0~100), unlockingDuration: unlocking duration (for example, the unlocking duration is 6 seconds, then unlocking is not allowed within 6 seconds)

///cn:
/// 蓝牙开锁（可自定义多个请求参数）
/// @param params 自定义蓝牙开锁请求参数
/// @param block 结果回调，power：门锁电量（0~100），unlockingDuration：开锁持续时间(例如开锁持续时间为6秒，则6秒内不允许开锁)
+ (void)unlockWithParams:(HXUnlockParams *)params
         completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, NSString *mac, int power, int unlockingDuration))block;

#pragma mark -蓝牙关锁 Bluetooth close lock
///en:
/// Bluetooth close lock (note: only some Bluetooth locks support triggering the cylinder to close the lock, please judge whether the door lock supports the lock according to the actual situation)
/// @param mac Bluetooth lock mac address
/// @param block Result callback

///cn:
/// 蓝牙关锁（注意：仅部分蓝牙锁支持触发锁芯关锁，请根据实际情况判断门锁是否支持关锁）
/// @param mac 蓝牙锁Mac
/// @param block 结果回调
+ (void)closeLockWithMac:(NSString *)mac
         completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, NSString *mac))block;

#pragma mark -添加密码/指纹/卡片/遥控钥匙 Add password/fingerprint/card/remote key
///en:
/// Add password/fingerprint/card/remote key
/// @param addKeyParams Use "HXBLEAddPasswordKeyParams" to add password, and "HXBLEAddOtherKeyParams" to add fingerprint/card/remote control
/// @param block Result callback, keyObj, authTotal, and authCount are successfully valid, and multiple callbacks may be triggered. Adding a password and card will only trigger one callback;
/// statusCode: KSHStatusCode_Success indicates that the verification is successful, when keyObj has a value, it indicates that the key is successfully added;
/// keyObj: indicates the key information returned after adding the key successfully;
/// authTotal: the total number of verifications required (note: the number of verifications of fingerprints is different for different models of fingerprint heads, the first time adding the fingerprint key cannot confirm the total number of verifications, the default value of authTotal is 255);
/// authCount: How many times is the current verification;

///cn:
/// 添加密码/指纹/卡片/遥控钥匙
/// @param addKeyParams 添加密码使用”HXBLEAddPasswordKeyParams“，添加指纹/卡片/遥控使用"HXBLEAddOtherKeyParams"
/// @param block 结果回调，keyObj、authTotal、authCount成功有效，可能会触发多次回调，添加密码和卡片只会触发一次回调；
/// statusCode：KSHStatusCode_Success表示验证成功，当keyObj有值表示添加钥匙成功；
/// keyObj：表示添加钥匙成功返回的钥匙信息；
/// authTotal：需要验证总次数（注意：由于不同型号指纹头验证指纹的次数不一样，第一次添加指纹钥匙无法确认要验证的总数，authTotal默认值为255）；
/// authCount：当前验证处于第几次；
+ (void)addKey:(HXBLEAddKeyBaseParams *)addKeyParams completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, HXKeyModel *keyObj, int authTotal, int authCount))block;

#pragma mark -添加人脸钥匙到蓝牙锁中(支持设置有效期)
/// 添加人脸钥匙到蓝牙锁中(支持设置有效期)
/// - Parameters:
///   - dataParam: 人脸数据
///   - timeParam: 钥匙有效期（特别注意：keyGroupId为900的用户为管理员，只支持添加永久钥匙）
///   - lockMac: 门锁Mac
///   - block: 结果回调
+ (void)addFaceKeyDataParam:(SHBLEAddBigDataKeyParam *)dataParam
                  timeParam:(SHBLEKeyValidTimeParam *)timeParam
                    lockMac:(NSString *)lockMac
            completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, NSInteger currentIndex, int lockKeyId))block;

#pragma mark -添加人脸钥匙到蓝牙锁中(不支持设置有效期)
/// 添加人脸钥匙到蓝牙锁中(不支持设置有效期)
/// - Parameters:
///   - dataParam: 人脸数据
///   - lockMac: 门锁Mac
///   - block: 结果回调
+ (void)addFaceKeyDataParam:(SHBLEAddBigDataKeyParam *)dataParam
                    lockMac:(NSString *)lockMac
            completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, NSInteger currentIndex, int lockKeyId))block;

#pragma mark -添加指纹钥匙到蓝牙锁中(支持设置有效期)
/// 添加指纹钥匙到蓝牙锁中(支持设置有效期)
/// - Parameters:
///   - dataParam: 指纹数据
///   - timeParam: 钥匙有效期（特别注意：keyGroupId为900的用户为管理员，只支持添加永久钥匙）
///   - block: 结果回调
+ (void)addFingerprintKeyDataParam:(SHBLEAddBigDataKeyParam *)dataParam
                         timeParam:(SHBLEKeyValidTimeParam *)timeParam
                            locMac:(NSString *)lockMac
                   completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, NSInteger currentIndex, int lockKeyId))block;

#pragma mark -添加指纹钥匙到蓝牙锁中（不支持设置有效期）
/// 添加指纹钥匙到蓝牙锁中（不支持设置有效期）
/// - Parameters:
///   - dataParam: 指纹数据
///   - block: 结果回调
+ (void)addFingerprintKeyDataParam:(SHBLEAddBigDataKeyParam *)dataParam
                            locMac:(NSString *)lockMac
                   completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, NSInteger currentIndex, int lockKeyId))block;

#pragma mark -修改密码钥匙密码 Modify password key password
///en:
/// Modify password key password
/// @param newPassword New Password
/// @param lockKeyId The unique Id of the key in the door lock
/// @param lockMac Bluetooth lock mac address
/// @param block Result callback

///cn:
/// 修改密码钥匙密码
/// @param newPassword 新密码
/// @param lockKeyId 门锁中钥匙的唯一Id
/// @param lockMac 蓝牙锁mac地址
/// @param block 结果回调
+ (void)modifyKeyPassword:(NSString *)newPassword
                lockKeyId:(int)lockKeyId
                   locMac:(NSString *)lockMac
          completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason))block;

#pragma mark -禁用或激活钥匙 Set disable or enable key
///en:
/// Set disable or enable key
/// @param params Request parameters, please refer to HXSetKeyEnableParams for instructions
/// @param block Result callback

///cn:
/// 禁用或激活钥匙
/// @param params 请求参数，使用说明见HXSetKeyEnableParams
/// @param block 结果回调
+ (void)setKeyEnable:(HXSetKeyEnableParams *)params completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason))block;

#pragma mark -修改钥匙有效期 Modify the key validity period
///en:
/// Modify the key validity period (Note: Bluetooth lock protocol version bleProtocolVersion >= 13 supports this interface)
/// @param params Request parameters, see HXModifyKeyTimeParams for instructions
/// @param block Result callback

///cn:
/// 修改钥匙有效期（注意：蓝牙锁协议版本bleProtocolVersion >= 13支持该接口）
/// @param params 请求参数，使用说明见HXModifyKeyTimeParams
/// @param block 结果回调
+ (void)modifyKeyTime:(HXModifyKeyTimeParams *)params completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason))block;

#pragma mark -删除钥匙 Delete key
///en:
/// Delete key
/// @param params Request parameters, see HXDeleteKeyParams for instructions
/// @param block Result callback

///cn:
/// 删除钥匙
/// @param params 请求参数，使用说明见HXDeleteKeyParams
/// @param block 结果回调
+ (void)deleteKey:(HXDeleteKeyParams *)params completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason))block;

#pragma mark -设置蓝牙锁系统参数 Set Bluetooth lock system parameters
///en:
/// Set Bluetooth lock system parameters
/// @param params Request parameters, please refer to HXSetSystemParameters for instructions
/// @param block Result callback

///cn:
/// 设置蓝牙锁系统参数
/// @param params 请求参数，使用说明见HXSetSystemParameters
/// @param block 结果回调
+ (void)setSystemParameters:(HXSetSystemParameters *)params completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason))block;

#pragma mark -校准蓝牙锁时间和手机一致 Calibrate the Bluetooth lock time to be the same as the mobile phone
///en:
/// Calibrate the Bluetooth lock time to be the same as the mobile phone
/// @param mac Bluetooth lock mac address
/// @param block Result callback

///cn:
/// 校准蓝牙锁时间和手机一致
/// @param mac 蓝牙锁mac地址
/// @param block 结果回调
+ (void)synchronizeTimeWithMac:(NSString *)mac completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason))block;

#pragma mark -获取蓝牙锁操作记录总数量 Get the total number of Bluetooth lock operation records
///en:
/// Get the total number of Bluetooth lock operation records
/// @param lockMac Bluetooth lock mac address
/// @param block Result callback, total is successful and valid, indicating the total number of records

///cn:
/// 获取蓝牙锁操作记录总数量
/// @param lockMac 蓝牙锁mac地址
/// @param block 结果回调，total成功有效，表示记录总数
+ (void)getOperationRecordCountWithLockMac:(NSString *)lockMac completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, int total))block;

#pragma mark -获取蓝牙锁操作记录列表 Get a list of Bluetooth lock operation records
///en:
/// Get a list of Bluetooth lock operation records (If there is a lot of data, it will be returned multiple times)
/// @param lockMac Bluetooth lock mac address
/// @param startIndex Read the start index of the record (note: the index of the latest record is 0)
/// @param count get count
/// @param block Result callback
///        logArray: log information;
///        If moreData is YES, it means that there will be more data in the future, and the interface will continue to trigger the callback. NO means that the data synchronization is completed this time.

///cn:
/// 获取蓝牙锁操作记录列表（数据较多时会分多次返回）
/// @param lockMac 蓝牙锁mac地址
/// @param startIndex 读取记录的开始下标（注意：最新一条记录下标为0）
/// @param count 获取数量，一般填10
/// @param logVersion 1表示第一代门锁操作记录，2表示第二代门锁操作记录，根据门锁DNA信息中的menuFeature第三个bit位为1表示门锁仅支持第二代操作记录，否则表示门锁仅支持第一代操作记录
/// @param block 结果回调
///        logArray表示日志信息；
///        moreData为YES表示后续还有更多数据，该接口会继续触发回调，NO表示本次数据同步完成
///        logVersion值为1表示第一代门锁操作记录，值为2表示第二代门锁操作记录
+ (void)getOperationRecordListWithLockMac:(NSString *)lockMac
                               startIndex:(int)startIndex
                                    count:(int)count
                               logVersion:(int)logVersion
                          completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, NSArray *logArray, BOOL moreData, int logVersion))block;

#pragma mark -获取蓝牙锁钥匙列表 Get a list of bluetooth lock keys
///en:
/// Get a list of bluetooth lock keys (If there is a lot of data, it will be returned multiple times)
/// @param lockMac Bluetooth lock mac address
/// @param block Result callback
///        keyObj: key information,
///        total: Total number of keys,
///        If moreData is YES, it means that there will be more data in the future, and the interface will continue to trigger the callback, and NO means that the data synchronization is completed.

///cn:
/// 获取蓝牙锁钥匙列表（数据较多时会分多次返回）
/// @param lockMac 蓝牙锁mac地址
/// @param block 结果回调
///        keyObj表示钥匙信息，
///        total表示钥匙总数，
///        moreData为YES表示后续还有更多数据，该接口会继续触发回调，NO表示数据同步完成
+ (void)getKeyListWithLockMac:(NSString *)lockMac
              completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, HXKeyModel *keyObj, int total, BOOL moreData))block;

#pragma mark -获取蓝牙锁系统参数和状态信息 Get Bluetooth lock system parameters and status information
///en:
/// Get Bluetooth lock system parameters and status information
/// @param mac Bluetooth lock mac address
/// @param block Result callback, deviceStatus is successful and effective

///cn:
/// 获取蓝牙锁系统参数和状态信息
/// @param mac 蓝牙锁mac地址
/// @param block 结果回调，deviceStatus成功有效
+ (void)getDeviceStatusWithMac:(NSString *)mac completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, HXBLEDeviceStatus *deviceStatus))block;

#pragma mark -解除报警 Release alarm
///en:
/// Release alarm
/// @param releaseType Release alarm type
/// @param lockMac Bluetooth lock mac address
/// @param block Result callback

///cn:
/// 解除报警
/// @param releaseType 解除报警类型
/// @param lockMac 蓝牙锁mac地址
/// @param block 结果回调
+ (void)releaseAlarmType:(KSHReleaseType)releaseType lockMac:(NSString *)lockMac completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason))block;

#pragma mark -获取蓝牙模块的固件版本号 Get the firmware version number of the Bluetooth module
///en:
/// Get the firmware version number of the Bluetooth module
/// @param lockMac Bluetooth lock mac address
/// @param block Result callback, the version is successful and valid, indicating the version number of the Bluetooth lock firmware

///cn:
/// 获取蓝牙模块的固件版本号
/// @param lockMac 蓝牙锁mac地址
/// @param block 结果回调，version成功有效，表示蓝牙锁固件版本号
+ (void)getFirmwareVersionWithLockMac:(NSString *)lockMac completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, NSString *version))block;

#pragma mark -获取DNA信息（设备基类信息） Get DNA information (device base class information)
///en:
/// Get DNA information (device base class information)
/// Generally, this interface is called to update the device information after the firmware upgrade is successful
/// @param lockMac Bluetooth lock mac address
/// @param block Result callback, the deviceBase is successful and valid, indicating the basic information of the Bluetooth lock

///cn:
/// 获取DNA信息（设备基类信息）
/// 一般在固件升级成功后调用该接口更新设备信息
/// @param lockMac 蓝牙锁mac地址
/// @param block 结果回调，deviceBase成功有效，表示蓝牙锁基本信息
+ (void)getDNAInfoWithLockMac:(NSString *)lockMac completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, HXBLEDeviceBase *deviceBase))block;

#pragma mark -蓝牙锁退出命令 Bluetooth lock exit command
///en:
/// Bluetooth lock exit command
/// (Used for time-consuming commands, exiting the operation in the middle of the operation, including exiting the synchronization key / exiting the synchronization Bluetooth lock operation record / exiting the key addition, etc.)
/// @param lockMac Bluetooth lock mac address
/// @param block Result callback

///cn:
/// 蓝牙锁退出命令
/// （用于耗时较长的命令，在操作中途退出操作，包括退出同步钥匙/退出同步蓝牙锁操作记录/退出添加钥匙等）
/// @param lockMac 蓝牙锁的mac
/// @param block 结果回调
+ (void)exitCmdWithLockMac:(NSString *)lockMac completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason))block;

#pragma mark -触发蓝牙锁的NB-IoT模块登录服务器 Trigger the external NB-IoT module of the Bluetooth lock to log in to the server
///en:
/// Trigger the external NB-IoT module of the Bluetooth lock to log in to the server
/// (Note: rfModuleType==kHXRFModuleType_HXJNBDX is required to be allowed to call this interface)
/// @param lockMac Bluetooth lock mac address
/// @param tokenId The tokenId of the NBIoT login server. The tokenId needs to be obtained from the HXJIOT server through the interface
/// @param block Result callback,
///        Success means that the command is sent to the Bluetooth lock successfully,
///        Subsequent NB-IoT login server results need to be sent by the server to push notification App

///cn:
/// 触发蓝牙锁的NB-IoT模块登录服务器
/// (注意：需要满足rfModuleType==kHXRFModuleType_HXJNBDX才允许调用该接口)
/// @param lockMac 蓝牙锁mac地址
/// @param tokenId NBIoT登录服务器的tokenId，该tokenId需要通过接口向慧享佳服务器获取
/// @param block 结果回调，
///        成功表示命令发送给蓝牙锁成功，
///        后续NB-IoT登录服务器结果需要由服务器下发推送通知App
+ (void)triggerNBIoTModuleLoginToServerWithMac:(NSString *)lockMac
                                       tokenId:(NSString *)tokenId
                               completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason))block;

#pragma mark -触发蓝牙锁的433模块进入配对状态 The 433 module that triggers the Bluetooth lock enters the pairing state
///en:
/// The 433 module that triggers the Bluetooth lock enters the pairing state
/// (Note: rfModuleType==kHXRFModuleType_TCV433 is required to allow calling this interface)
/// @param lockMac Bluetooth lock mac address
/// @param block Result callback, Success means that the command is sent to the Bluetooth lock successfully, waiting for the 433 Bluetooth gateway to pair the Bluetooth lock 433 module

///cn:
/// 触发蓝牙锁的433模块进入配对状态
/// (注意：需要满足rfModuleType==kHXRFModuleType_TCV433才允许调用该接口)
/// @param lockMac 蓝牙锁的mac
/// @param block 结果回调，成功表示命令发送给蓝牙锁成功，等待433蓝牙网关配对蓝牙锁433模块
+ (void)trigger433ModuleStartsPairingWithMac:(NSString *)lockMac completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason))block;

#pragma mark -尝试连接蓝牙锁 Try to connect the bluetooth lock
///en:
/// Try to connect the bluetooth lock
/// (It can be used to automatically connect to the Bluetooth device after entering the UI page to speed up the control of the Bluetooth lock)
/// @param lockMac Bluetooth lock mac address
/// @param block Result callback

///cn:
/// 尝试连接蓝牙锁
///（可用于进入UI页面后自动连接蓝牙设备，加快对蓝牙锁的控制速度）
/// @param lockMac 蓝牙锁mac地址
/// @param block 结果回调
+ (void)connectPeripheralWithMac:(NSString *)lockMac completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason))block;

#pragma mark -尝试主动断开手机与蓝牙锁的连接 Try to actively disconnect the phone from the Bluetooth lock
///en:
/// Try to actively disconnect the phone from the Bluetooth lock
/// (If there is a task between the current App and the Bluetooth lock that has not been processed (such as unlocking...), the connection will not be disconnected, otherwise the connection will be disconnected)
/// @param lockMac Bluetooth lock mac address

///cn:
/// 尝试主动断开手机与蓝牙锁的连接
/// (如果当前App与蓝牙锁之间有任务未处理完（例如开锁中..），则不会断开连接，否则会断开连接)
/// @param lockMac 蓝牙锁的mac
+ (void)tryDisconnectPeripheralWithMac:(NSString *)lockMac;

#pragma mark -直接断开手机与蓝牙锁的连接 Disconnect the phone directly from the Bluetooth lock
///en:
/// Disconnect the phone directly from the Bluetooth lock
/// @param lockMac Bluetooth lock mac address

///cn:
/// 直接断开手机与蓝牙锁的连接
/// @param lockMac 蓝牙锁mac地址
+ (void)disconnectPeripheralWithMac:(NSString *)lockMac;

#pragma mark -获取手机与蓝牙锁的连接状态 Get the connection status of the mobile phone and the Bluetooth lock
///en:
/// Get the connection status of the mobile phone and the Bluetooth lock
/// @param lockMac Bluetooth lock mac address
/// @return YES: connected, NO: not connected

///cn:
/// 获取手机与蓝牙锁的连接状态
/// @param lockMac 蓝牙锁mac地址
/// @return YES：已连接，NO：未连接
+ (BOOL)getConnectStatusWithLockMac:(NSString *)lockMac;


#pragma mark -删除蓝牙锁 Delete Bluetooth lock
///en:
/// Delete Bluetooth lock
/// @param lockMac Bluetooth lock mac address
/// @param block Result callback

///cn:
/// 删除蓝牙锁
/// @param lockMac 蓝牙锁mac地址
/// @param block 结果回调
+ (void)deleteDeviceWithMac:(NSString *)lockMac completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason))block;


#pragma mark -设置蓝牙锁使用有效期 Set the validity period of the Bluetooth lock
///en:
/// Set the validity period of the Bluetooth lock. After the expiration, the Bluetooth lock will not work.
/// @param lockMac Bluetooth lock mac address
/// @param remainningTime The remaining valid time (Unit: second)
///        The value is less than 0xFFFFFFFF: it means that the countdown will start after the setting is successful. When the remainingTime is 0, you need to use this command to reactivate to use the Bluetooth lock;
///        0xFFFFFFFF: indicates permanent validity.
/// @param promptDays The number of days to remind in advance (Unit: day), the value range is: 1 ~ 9;
/// @param block Result callback
/// @discussion Conditions of use ⚠️: (HXBLEDevice.menuFeature & kHXMenuFeature_supportSetLockExpirationTime != 0) The method is allowed to be used only when the condition is established (that is, the device supports the setting)
/// @discussion Usage scenario: It can be used in specific scenarios in the pre-sale door lock market. If the user does not pay the door lock fee after the expiration date, the door lock cannot be used after the trial period ends.

///cn:
/// 设置蓝牙锁使用有效期，到期后蓝牙锁无法运行。
/// @param lockMac 蓝牙锁mac地址
/// @param remainningTime 剩余有效时间，单位:秒；
///        值小于0xFFFFFFFF：表示设置成功后，将开始倒计时，当remainningTime为0时，需要使用该命令重新激活才能使用蓝牙锁；
///        0xFFFFFFFF：表示永久有效。
/// @param promptDays 提前提醒天数，单位天；取值范围为：1 ~ 9；
/// @param block 结果回调
/// @discussion 使用条件⚠️：(HXBLEDevice.menuFeature & kHXMenuFeature_supportSetLockExpirationTime != 0) 条件成立（即设备支持设置）才允许使用该方法
/// @discussion 使用场景：可用于预售门锁市场特定场景，若用户在超过有效期没有支付门锁费用，则门锁在试用期结束后不能使用
+ (void)setLockExpirationTimeWithLockMac:(NSString *)lockMac
                          remainningTime:(long)remainningTime
                              promptDays:(int)promptDays
                         completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason))block;

#pragma mark -获取蓝牙锁使用有效期 Get the validity period of the Bluetooth lock
///en:
/// Get the validity period of the Bluetooth lock
/// @param lockMac Bluetooth lock mac address
/// @param block Result callback
///        remainningTime: The remaining valid time (Unit: second)
///        promptDays: The number of days to remind in advance (Unit: day)
/// @discussion Conditions of use⚠️: (HXBLEDevice.menuFeature & kHXMenuFeature_supportSetLockExpirationTime != 0) Only when the condition is established (the device supports the setting) is the method allowed to be used

///cn:
/// 获取蓝牙锁使用有效期
/// @param lockMac 蓝牙锁mac地址
/// @param block 结果回调
///        remainningTime：剩余有效时间，单位秒
///        promptDays：提前提醒天数，单位天
/// @discussion 使用条件⚠️：(HXBLEDevice.menuFeature & kHXMenuFeature_supportSetLockExpirationTime != 0) 条件成立（即设备支持设置）才允许使用该方法
+ (void)getLockExpirationTimeWithLockMac:(NSString *)lockMac
                         completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, long remainningTime, int promptDays))block;


#pragma mark - Wi-Fi模组配网 Wi-Fi module configuration to the network
#pragma mark *********************

/// en:
///  Wi-Fi module distribution network
///  @param param request parameters
///  @param block sends the result, Note: you need to add notification KSHNotificationWiFiNetworkConfig and judge the network configuration result according to the returned parameters

/// cn:
///  Wi-Fi模组配网
///  @param param 请求参数
///  @param block 发送结果， 注意：正常情况下需要监听通知 KSHNotificationWiFiNetworkConfig 并根据返回参数判断配网结果，
///  如果配网的设备时取电开关，则无需监听通知：KSHNotificationWiFiNetworkConfig，直接根据回调判断配网结果
+ (void)configWiFiLockNetworkWithParam:(SHBLENetworkConfigParam *)param
                       completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, NSString *mac, int wifiStatus, NSString *rfModuleMac, NSString *originalRfModuleMac))block;

#pragma mark -设置人脸锁人体感应的灵敏度
#pragma mark *********************


/// 设置人脸锁人体感应的灵敏度
/// - Parameters:
///   - level: 人体感应的灵敏度等级
///   - lockMac: 蓝牙锁Mac地址
///   - block: 结果回调
+ (void)setFaceLockBodyDetectionSensitivityWithLevel:(kDetectionSensitivityLevel)level
                                             lockMac:(NSString *)lockMac
                                     completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, NSString *lockMac, kDetectionSensitivityLevel level))block;

#pragma mark - 设置酒店锁系统参数（该接口主要用于酒店锁，其它类型锁部分功能适用）
#pragma mark *********************

/// 设置锁其它系统参数（该接口主要用于酒店锁，其它类型锁部分功能适用）
/// - Parameters:
///   - param: 请求参数
///   - block: 结果回调
+ (void)setHotelLockSystemParam:(SHBLEHotelLockSystemParam *)param completionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason))block;


#pragma mark - 读取酒店锁系统参数（该接口主要用于酒店锁，其它类型锁部分功能适用）
#pragma mark *********************

/// 读取酒店锁系统参数（该接口主要用于酒店锁，其它类型锁部分功能适用）
/// - Parameters:
///   - lockMac: 蓝牙锁Mac地址
///   - block: 结果回调
+ (void)getHotelLockSystemParamWithLockMac:(NSString *)lockMac complectionBlock:(void(^)(KSHStatusCode statusCode, NSString *reason, SHBLEHotelLockSystemParam *param))block;


@end


