//
//  SHGlobalHeader.h
//  SmartHomeSDK
//
//  Created by JQ on 2017/2/20.
//  Copyright © 2017年 JQ. All rights reserved.
//

#ifndef SHGlobalHeader_h
#define SHGlobalHeader_h

/**
 Operation Type
 操作标识
 */
typedef NS_ENUM(int, KSHModifyType) {
    /**
     Add
     新增
     */
    KSHModifyType_Add = 1,
    /**
     Modify
     修改
     */
    KSHModifyType_Modify = 2,
    /**
     Delete
     删除
     */
    KSHModifyType_Delete = 3,
};

/**
 Key User Type
 钥匙用户类型
 */
typedef NS_ENUM(int, KSHKeyUserType) {
    /**
     Unknow
     未知用户类型
     */
    KSHKeyUserType_Unknown = 0,
    /**
     Admin
     管理员
     */
    KSHKeyUserType_Admin = 1,
    /**
     General user
     普通用户
     */
    KSHKeyUserType_User = 2,
    /**
     Temp user
     临时用户
     */
    KSHKeyUserType_TemporaryUser = 4,
};

/**
 Lock Type
 门锁类型
 */
typedef NS_ENUM(int, KSHLockType) {
    /**
     All Type
     所有锁
     */
    KSHLockType_All = -1,
    /**
     Gateway Lock
     网关锁
     */
    KSHLockType_GatewayLock = 1,
    /**
     Wi-Fi Lock
     WiFi锁
     */
    KSHLockType_WiFiLock = 2,
    /**
     Bluetooth Lock
     蓝牙锁
     */
    KSHLockType_BluetoothLock = 3,
    /**
     NB-IoT Lock
     NBIoT锁
     */
    KSHLockType_NBIoTLock = 4,
    /**
     Bluetooth Combination Lock
     蓝牙组合锁
     */
    KSHLockType_CombinationLock = 5,
};

/**
 Gateway Type
 网关类型
 */
typedef NS_ENUM(int, KSHGatewayType) {
    /**
     Bluetooth + 433 Gateway
     蓝牙 + 433 网关
     */
    KSHGatewayType_BLE433Gateway = 1,
    /**
     433 Gateway
     433网关
     */
    KSHGatewayType_433Gateway = 2,
    /**
     Bluetooth Gateway
     蓝牙网关
     */
    KSHGatewayType_BLEGateway = 3,
};

/**
 Device Firmware Type
 固件类型
 */
typedef NS_ENUM(int, kSHFirmwareType) {
    /**
     Gateway
     网关
     */
    kSHFirmwareType_Gateway = 0,
    /**
     Gateway Lock
     网关锁
     */
    kSHFirmwareType_GatewayLock = 1,
    /**
     Wi-Fi Lock
     WI-FI锁
     */
    kSHFirmwareType_WIFILock = 2,
    /**
     Bluetooth Lock
     蓝牙锁
     */
    kSHFirmwareType_BluetoothLock = 3,
    /**
     Bluetooth Module
     蓝牙模块
     */
    kSHFirmwareType_BluetoothModule = 4,
};

/** Bluetooth lock external module type */
/** 蓝牙锁外接模组类型  */
typedef NS_ENUM (int, kHXRFModuleType) {
    /** 433, can be bound to 433 Bluetooth gateway to achieve networking */
    /** 433，可绑定433蓝牙网关实现联网  */
    kHXRFModuleType_TCV433 = 0,
    /** Not yet used */
    /** 暂未使用  */
    kHXRFModuleType_LPRX315 = 1,
    /** Not yet used */
    /** 暂未使用  */
    kHXRFModuleType_TCV868 = 2,
    /** Wi-Fi module */
    /** 外接Wi-Fi模组  */
    kHXRFModuleType_HXJWIFI = 4,
    /** NB-IoT, can be directly connected to the Internet */
    /** NB-IoT，可直接联网  */
    kHXRFModuleType_HXJNBDX = 5,
    /** Lora module */
    /** LoRa模组  */
    kHXRFModuleType_HXJLoRa = 6,
    /** Not yet used */
    /** 暂未使用  */
    kHXRFModuleType_HXJZigBee = 7,
    /** 支持身份证云解析的Wi-Fi模组  */
    kHXRFModuleType_HXJWIFIZJJX = 8,
    /** NB-IoT, can be directly connected to the Internet */
    /** NBIoT模组，MQTT Protocol 支持MQTT协议 */
    kHXRFModuleType_HXJNBMQTT = 9,
    /** NB-IoT, LWM2M Protocol, can be directly connected to the Internet */
    /** NBIoT模组，支持LWM2M协议 */
    kHXRFModuleType_HXJNBLWM2M = 10,
    /** LTEUE-Category1（Cat.1）模组，Cat.1，可以称为“低配版”的 4G 终端，上行峰值速率5Mbit/s，下行峰值速率10Mbit/s，属于蜂窝物联网，是广域网  */
    kHXRFModuleType_HXJCat1= 11,
    /** There is no wireless module, it can be bound to a Bluetooth gateway to connect network */
    /** 没有无线模组，可绑定蓝牙网关实现联网  */
    kHXRFModuleType_Empty = 255,
};

/** Bluetooth lock function */
/** 蓝牙锁特性  */
typedef NS_OPTIONS (int, kHXLockFunctionType) {
    /** Support fingerprint unlock */
    /** 支持指纹开锁  */
    kHXLockFunctionType_supportFingerprint = 1 << 0,//第 0 bit
    /** Support entering password to unlock in the door lock */
    /** 支持在门锁中录入密码开锁  */
    kHXLockFunctionType_supportPassword = 1 << 1,//第 1 bit
    /** Support card unlock */
    /** 支持卡片开锁  */
    kHXLockFunctionType_supportCard = 1 << 2,//第 2 bit
    /** Support remote unlocking */
    /** 支持遥控开锁  */
    kHXLockFunctionType_supportRemoteControl = 1 << 3,//第 3 bit
    /** Support face unlocking */
    /** 支持人脸开锁  */
    kHXLockFunctionType_supportFace = 1 << 6,//第 6 bit
    /** Support voice */
    /** 支持语音  */
    kHXLockFunctionType_supportVoice = 1 << 9,//第 9 bit
    /** Support password unlocking generated by algorithm */
    /** 支持算法生成的密码开锁  */
    kHXLockFunctionType_supportOfflinePassword = 1 << 11,//第 11 bit
};

/** Menu feature */
/** 菜单属性  */
typedef NS_OPTIONS(int, kHXMenuFeature) {
    /** The door lock operation record is the second representative method */
    /** 门锁操作记录为第二代表达方式  */
    kHXMenuFeature_supportOperationRecord2 = 1 << 1,//2，表示第 1 bit
    
    /** Support setting the validity period of the Bluetooth lock, the Bluetooth lock will not work after the expiration
     (It can be used in specific scenarios in the pre-sale door lock market. If the user does not pay the door lock fee after the expiration date, the door lock cannot be used after the trial period ends)
     */
    /** 支持设置蓝牙锁使用有效期，到期后蓝牙锁无法运行
     （可用于预售门锁市场特定场景，若用户在超过有效期没有支付门锁费用，则门锁在试用期结束后不能使用）
     */
    kHXMenuFeature_supportSetLockExpirationTime = 1 << 2,//4，表示第 2 bit
    /**
     该bit值为1表示支持第二代门锁操作记录
     */
    kHXMenuFeature_supportSecondEdition = 1 << 3,//8，表示第 3 bit

};

/** Wireless module function */
/** 无线模组功能  */
typedef NS_OPTIONS(int, kHXRFModuleFunction) {
    /** The module supports remote control function */
    /** 模组支持遥控器功能 */
    kHXRFModuleFunction_supportRemoteControl = 1 << 0,//第 0 bit
    /** The module supports FM function */
    /** 模组支持调频功能 */
    kHXRFModuleFunction_supportFM = 1 << 2,//第 1 bit
    /** Support internal protocol transparent transmission function (if it is NB module, it supports AT command) */
    /** 支持内部协议透传功能（若是NB模组，表示支持AT指令） */
    kHXRFModuleFunction_supportThroughCmd = 1 << 3,//第 1 bit
};

#endif /* SHGlobalHeader_h */




