package com.example.wise_apartment.utils;

import android.content.Context;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.os.Build;
import android.util.Log;

import java.util.HashMap;
import java.util.Map;

import io.flutter.plugin.common.MethodChannel.Result;
import com.example.hxjblinklibrary.blinkble.profile.client.HxjBleClient;
import com.example.hxjblinklibrary.blinkble.entity.requestaction.BlinkyAuthAction;
import com.example.hxjblinklibrary.blinkble.profile.other.ATConfigHelper;
import com.example.hxjblinklibrary.blinkble.profile.other.Cat1ATConfigHelper;
import com.example.wise_apartment.BuildConfig;

public class DeviceInfoManager {
    private static final String TAG = "DeviceInfoManager";
    private final Context context;
    private final HxjBleClient bleClient;

    public DeviceInfoManager(Context context, HxjBleClient client) {
        this.context = context;
        this.bleClient = client;
    }

    public void getDeviceInfo(Result result) {
        Map<String, Object> info = new HashMap<>();
        info.put("manufacturer", Build.MANUFACTURER);
        info.put("model", Build.MODEL);
        info.put("brand", Build.BRAND);
        info.put("sdkInt", Build.VERSION.SDK_INT);
        info.put("release", Build.VERSION.RELEASE);
        info.put("packageName", context.getPackageName());
        result.success(info);
    }

    public void getAndroidBuildConfig(Result result) {
        Map<String, Object> config = new HashMap<>();
        try {
            // These fields are generated by Gradle in the plugin's BuildConfig
            config.put("applicationId", BuildConfig.BUILD_APPLICATION_ID);
            config.put("namespace", BuildConfig.BUILD_NAMESPACE);
            config.put("versionName", BuildConfig.BUILD_VERSION_NAME);
            config.put("versionCode", Integer.parseInt(BuildConfig.BUILD_VERSION_CODE));
            config.put("minSdk", Integer.parseInt(BuildConfig.BUILD_MIN_SDK));
            config.put("targetSdk", Integer.parseInt(BuildConfig.BUILD_TARGET_SDK));
            config.put("compileSdk", Integer.parseInt(BuildConfig.BUILD_COMPILE_SDK));
        } catch (Exception e) {
            Log.e(TAG, "Error reading BuildConfig", e);
            config.put("error", "Info missing or parse error: " + e.getMessage());
            try {
                PackageInfo pInfo = context.getPackageManager().getPackageInfo(context.getPackageName(), 0);
                config.put("versionName", pInfo.versionName);
                config.put("versionCode", pInfo.versionCode);
            } catch (PackageManager.NameNotFoundException ex) {}
        }
        result.success(config);
    }

    public void getNBIoTInfo(Map<String, Object> args, final Result result) {
        Log.d(TAG, "getNBIoTInfo called");
        BlinkyAuthAction auth = PluginUtils.createAuthAction(args);
       
        ATConfigHelper helper = new ATConfigHelper(context, bleClient);
        helper.startSetting(auth, new ATConfigHelper.ATCallBack() {
            @Override
            public void onAtGetSuccess(int rssi, String imsi, String imei) {
                Map<String, Object> res = new HashMap<>();
                res.put("rssi", rssi);
                res.put("imsi", imsi);
                res.put("imei", imei);
                result.success(res);
            }
            @Override
            public void onError(String s) {
                Log.e(TAG, "getNBIoTInfo error: " + s);
                result.error("ERROR", s, null);
            }
        });
    }

    public void getCat1Info(Map<String, Object> args, final Result result) {
        Log.d(TAG, "getCat1Info called");
        BlinkyAuthAction auth = PluginUtils.createAuthAction(args);
       
        Cat1ATConfigHelper helper = new Cat1ATConfigHelper(context, bleClient);
        helper.start(auth, new Cat1ATConfigHelper.Cat1ATCallBack() {
            @Override
            public void onAtGetSuccess(String iccid, String imei, String imsi, String rssi, String rsrp, String sinr) {
                Map<String, Object> res = new HashMap<>();
                res.put("iccid", iccid);
                res.put("imei", imei);
                res.put("imsi", imsi);
                res.put("rssi", rssi);
                res.put("rsrp", rsrp);
                res.put("sinr", sinr);
                result.success(res);
            }
            @Override
            public void onError(String s) {
                Log.e(TAG, "getCat1Info error: " + s);
                result.error("ERROR", s, null);
            }
        });
    }
}
